LK-1-5 Lesson 1 Task 5  time in space Yuri Gagarin
AlexOlefir/LessonKotlin pull request #5
Opened 2023-07-15 21:14 UTC by AlexOlefir

2023-07-17 06:42 UTC, ievetrov requested changes

2023-07-17 06:42 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson1-task5.kt
> +    println("0$hour:$remainderMinute:0$remainderSeconds")
в данном случае когда у нас будет число секунд больше 9 здесь будет трехзначное число)

попробуй использовать `String.format` для вывода

2023-07-17 13:44 UTC, AlexOlefir commented on src/main/kotlin/lesson_1/lesson1-task5.kt
> +    println("0$hour:$remainderMinute:0$remainderSeconds")
Не знаю, вообще нет вариантов. Даже если я перевожу переменные с помощью toString в формат строки, результат не меняется.

2023-07-17 14:13 UTC, AlexOlefir commented on src/main/kotlin/lesson_1/lesson1-task5.kt
Ну наверное это не то решение, которое должно быть, но единственное, которое пришло мне в голову.
Но работает)

2023-07-18 14:14 UTC, ievetrov requested changes

2023-07-18 14:14 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson1-task5.kt
> +    var proverkaHour = "0"
посчитано все правильно, а проверки ниже вообще не нужны) можно сделать таким образом
`println(String.format("%02d:%02d:%02d", hour, remainderMinute, remainderSeconds))`

и почистить код, чтобы переменные назывались единообразно)

2023-07-20 04:15 UTC, ievetrov approved these changes

2023-07-20 05:40 UTC, merged